# Generated by Django 2.2.4 on 2020-04-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments_posted_to', to='main.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages_posted_to', to='main.User'),
            preserve_default=False,
        ),
    ]
